### ISSUE TITLE
optimize cpdef read(self, typeName)

### ISSUE THREAD

**Issue by MichaelHinrichs** [ChronoMonochrome/RGSSAD-decryptor#2]
I saw a todo comment with no issue, so I made this.

**Comment by ChronoMonochrome** [comment]
This project is no longer maintained, but feel free to send a PR.
Optimizing functions like read() could improve performance, but it didn't work as easily when replacing the code with a low-level functions calls (like memcpy and using char* type), so it was reverted back to pure python version.
It might be worthwhile reimplementing the whole thing in a language like C++ probably, than having to deal with Cython tbh.
